DFKASSA_CONTRACT_ADDRESS_ETH_MAINNET = "0x9980A2622a257A5Ab593eaD7adcBc99F37f6C744"
DFKASSA_CONTRACT_ADDRESS_BSC_MAINNET = "0x9980A2622a257A5Ab593eaD7adcBc99F37f6C744"
DFKASSA_CONTRACT_ADDRESS_POLYGON_MAINNET = "0x9980A2622a257A5Ab593eaD7adcBc99F37f6C744"
DFKASSA_CONTRACT_ADDRESS_ARBITRUM_MAINNET = "0x9980A2622a257A5Ab593eaD7adcBc99F37f6C744"
DFKASSA_CONTRACT_ADDRESS_OPTIMISM_MAINNET = "0x9980A2622a257A5Ab593eaD7adcBc99F37f6C744"
DFKASSA_CONTRACT_ADDRESS_GOERLI_TESTNET = "0xeDB7a8A4d2189Cc632AF6AcaFE6eE81239C2C7df"

DFKASSA_CONTRACT_ABI = '[{"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"payload","type":"uint256"},{"indexed":true,"internalType":"address","name":"merchant","type":"address"},{"indexed":false,"internalType":"uint256","name":"amount","type":"uint256"},{"indexed":false,"internalType":"address","name":"token","type":"address"},{"components":[{"internalType":"address","name":"reciever","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"indexed":false,"internalType":"struct Tip[]","name":"tips","type":"tuple[]"}],"name":"NewPayment","type":"event"},{"inputs":[{"internalType":"address payable","name":"_merchant","type":"address"},{"internalType":"address","name":"_token","type":"address"},{"internalType":"uint256","name":"_amount","type":"uint256"},{"internalType":"uint256","name":"_payload","type":"uint256"},{"components":[{"internalType":"address","name":"reciever","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"}],"internalType":"struct Tip[]","name":"_tips","type":"tuple[]"}],"name":"pay","outputs":[],"stateMutability":"payable","type":"function"}]'

TOKEN_USD_ORACLE_ADDRESS_ETH_MAINNET = "0xD96891EAE74489463aA3FA834dd3eC87c4E6C7a7"
TOKEN_USD_ORACLE_ADDRESS_BSC_MAINNET = "0xD96891EAE74489463aA3FA834dd3eC87c4E6C7a7"
TOKEN_USD_ORACLE_ADDRESS_POLYGON_MAINNET = "0xD96891EAE74489463aA3FA834dd3eC87c4E6C7a7"
TOKEN_USD_ORACLE_ADDRESS_ARBITRUM_MAINNET = "0xD96891EAE74489463aA3FA834dd3eC87c4E6C7a7"
TOKEN_USD_ORACLE_ADDRESS_OPTIMISM_MAINNET = "0xD96891EAE74489463aA3FA834dd3eC87c4E6C7a7"
TOKEN_USD_ORACLE_ADDRESS_GOERLI_TESTNET = "0x2db2e05340489d64ff441870925d998e247fe8f4"

TOKEN_USD_ORACLE_CONTRACT_ABI = '[{"inputs":[{"internalType":"address","name":"_token","type":"address"},{"internalType":"uint256","name":"_amount","type":"uint256"}],"name":"calcE18","outputs":[{"internalType":"uint256","name":"_priceInUsd","type":"uint256"},{"internalType":"uint256","name":"_amountInUsd","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"_token","type":"address"},{"internalType":"uint256","name":"_amount","type":"uint256"}],"name":"calcE2","outputs":[{"internalType":"uint256","name":"_priceInUsd","type":"uint256"},{"internalType":"uint256","name":"_amountInUsd","type":"uint256"}],"stateMutability":"view","type":"function"}]'


ERC20_ABI = '[{"constant":true,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_spender","type":"address"},{"name":"_value","type":"uint256"}],"name":"approve","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"totalSupply","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_from","type":"address"},{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transferFrom","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"decimals","outputs":[{"name":"","type":"uint8"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_owner","type":"address"}],"name":"balanceOf","outputs":[{"name":"balance","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"symbol","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transfer","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"_owner","type":"address"},{"name":"_spender","type":"address"}],"name":"allowance","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"payable":true,"stateMutability":"payable","type":"fallback"},{"anonymous":false,"inputs":[{"indexed":true,"name":"owner","type":"address"},{"indexed":true,"name":"spender","type":"address"},{"indexed":false,"name":"value","type":"uint256"}],"name":"Approval","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"from","type":"address"},{"indexed":true,"name":"to","type":"address"},{"indexed":false,"name":"value","type":"uint256"}],"name":"Transfer","type":"event"}]'
